---
title: "Hello R"
author: "Claudia Dominguez"
date: "Data 2401"
output: html_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```

### Exercise 1

*The data set contains 1,846 rows and 3 columns*

### Exercise 2

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

```{r plot-star}
library(tidyverse)
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()







```

```{r cor-star}
# Comparing Correlation Coefficients: "dino" vs. "star"
star_data %>%
  summarize(r = cor(x, y))

```

### Exercise 4

```{r}
library(tidyverse)
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()


```

```{r}
circle_data %>%
  summarize(r = cor(x, y))


```

### Exercise 5

```{r plot-all, fig.height=8, fig.width=10}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
  geom_point() +
  facet_wrap(~ dataset, ncol = 3) + 
  theme(legend.position = "none")
```

```{r cor-all}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```
